version: "3.7"

services:
  exporter:
    restart: always
    command: /usr/local/bin/python /app/reposupdate.py
    environment:
      - REPOS=freeCodeCamp/freeCodeCamp,cosmos/gaia
      - TOKEN=${TOKEN}
      - CACHE_TIMEOUT=300 # cache period on seconds
    build:
      context: ./
      dockerfile: ./build/Dockerfile
    image: repos_update
    ports:
      - 9853:9853
