version: "3.7"

services:
  exporter:
    command: /bin/bash `while [[ 1 == 1 ]]; do sleep 5; done
    environment:
      - REPOS=${REPOS}
      - TOKEN=${TOKEN}
      - CACHE_TIMEOUT=300 # cache period on seconds
    build:
      context: ./
      dockerfile: ./build/Dockerfile
    image: repos_update
    ports:
      - 9853:9853
